name: publishing
on:
  workflow_dispatch:

jobs:
  zenodo:
      runs-on: ubuntu-latest
      steps:
        - name: checkout
          uses: actions/checkout@v4
          with:
            path: dirty

        - run: |
            cd dirty
            pwd

        - name: Generate .zenodo.citation.json
          uses: citation-file-format/cffconvert-github-action@2.0.0
          with:
            args: "--format zenodo --infile CITATION.cff --outfile .zenodo.citation.json"

        - name: Merge .zenodo.extras.json into .zenodo.citation.json
          run: |
            cat .zenodo.citation.json .zenodo.extras.json | jq -s add -S --indent 4 > .zenodo.json

        - name: Create a draft snapshot of the repository contents on Zenodo using metadata
                from repository file .zenodo.json
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            ZENODO_SANDBOX_ACCESS_TOKEN: ${{ secrets.ZENODO_SANDBOX_ACCESS_TOKEN }}
          shell: bash
          run: |
            npm install
            npm run all

        - name: checkout
          uses: actions/checkout@v4
          with:
              path: ../clean

        - run: |
            cd ../clean
            pwd
