name: zenodraft
on:
  workflow_dispatch:
  # workflow-dispatch allows for triggering the workflow
  # manually via the Actions tab

jobs:

  publish:
      runs-on: ubuntu-latest
      steps:
        - name: checkout
          uses: actions/checkout@v2      
        - name: Create a draft snapshot of the repository contents on Zenodo using metadata
                from repository file .zenodo.json
          env:
            ZENODO_ACCESS_TOKEN: ${{ secrets.ZENODO_ACCESS_TOKEN }}
          uses: zenodraft/action@0.9.0
          with:
            collection: 5046392
            metadata: .zenodo.json
            publish: false
            sandbox: false
            upsert-doi: true
            upsert-location: identifiers[0]
