name: publishing
on:
  workflow_dispatch:

jobs:
  zenodo:
      env:
        ZENODO_SANDBOX_ACCESS_TOKEN: ${{ secrets.ZENODO_SANDBOX_ACCESS_TOKEN }}

      runs-on: ubuntu-latest
      steps:

        - name: Get a copy of the repo contents
          uses: actions/checkout@v4

        - name: Create preliminary zip
          run: |
            rm -rf .git
            zip -r -v zenodraft.zip .

        - name: Install self
          shell: bash
          run: |
            npm install
            npm run all
            npm install zenodraft-*.tgz -g
            zenodraft --version

        - name: Get prereserved DOI
          shell: bash
          run: |
            VERSION=$(zenodraft deposition create version 23750 --sandbox)
            echo $VERSION
            echo $VERSION >> "$GITHUB_ENV"
        #    PRERESERVED=$(zenodraft deposition show prereserved --sandbox $VERSION)
        #    echo $PRERESERVED >> "$GITHUB_ENV"

        #- name: Update CITATION.cff with prereserved DOI
        #  shell: bash
        #  run: |
        #    echo "PRERESERVED = $PRERESERVED"
        #    yq eval '.identifiers[0].value = "'$PRERESERVED'"' --inplace CITATION.cff --output-format yaml
        #    cat CITATION.cff

        #- name: Generate .zenodo.citation.json
        #  uses: citation-file-format/cffconvert-github-action@2.0.0
        #  with:
        #    args: "--format zenodo --infile CITATION.cff --outfile .zenodo.citation.json"

        #- name: Create a draft snapshot of the repository contents on Zenodo using metadata
        #        from repository file .zenodo.json
        #  shell: bash
        #  run: |
        #    set -e
        #    cat .zenodo.citation.json .zenodo.extras.json | jq -s add -S --indent 4 > .zenodo.json
        #    zip -u -v zenodraft.zip . CITATION.cff
        #    zenodraft file add --sandbox $VERSION zenodraft.zip
        #    zenodraft metadata update --sandbox $VERSION .zenodo.json
