name: testing
on:
  pull_request:
  push:

jobs:
  cli:
    env:
      ZENODO_SANDBOX_ACCESS_TOKEN: ${{ secrets.ZENODO_SANDBOX_ACCESS_TOKEN }}
      RECORD_ID: hello
  
    runs-on: ubuntu-latest
    steps:
      - name: get a copy of the repo contents
        uses: actions/checkout@v2

      - name: install the project's dependencies
        run: npm install

      - name: generate a distributable tarball
        run: npm run all

      - name: install the cli from the tarball
        run: sudo npm install -g zenodraft-*.tgz

      - name: create a new directory to do the testing in
        run: mkdir testing && cd testing

      - name: test creating a new draft deposition in a new collection on zenodo sandbox
        run: RECORD_ID=$(zenodraft --sandbox deposition create in-new-collection)

#       - name: test env vars
#         run: |
#           echo $RECORD_ID
#           echo ${RECORD_ID}
#           echo ${{RECORD_ID}}
#           echo ${{env.RECORD_ID}}

#       - name: show the complete details for the draft deposition
#         run: zenodraft --sandbox deposition show details ${RECORD_ID}

#       - name: show the deposition id for the draft deposition
#         run: zenodraft --sandbox deposition show latest ${RECORD_ID}

#       - name: show the prereserved doi for the draft deposition
#         run: zenodraft --sandbox deposition show prereserved ${RECORD_ID}
      # - name: 
      #   run: 
      # - name: 
      #   run: 
      # - name: 
      #   run: 
      # - name: 
      #   run: 
      # - name: 
      #   run: 
      # - name: 
      #   run: 
      # - name: 
      #   run: 
      # - name: 
      #   run: 
      # 
