name: testing
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  live-sandbox-cli:
  
    env:
      RECORD_ID: ""
      CONCEPT_ID: ""
      ZENODO_SANDBOX_ACCESS_TOKEN: ${{ secrets.ZENODO_SANDBOX_ACCESS_TOKEN }}

 
    runs-on: ubuntu-latest
    steps:
      - name: get a copy of the repo contents
        uses: actions/checkout@v2



      - name: install the project's dependencies
        run: npm install



      - name: generate a distributable tarball
        run: npm run all



      - name: install the cli from the tarball
        run: sudo npm install -g zenodraft-*.tgz



      - name: create a new directory to do the testing in
        run: mkdir testing && cd testing



      - name: test creating a new draft deposition in a new concept on zenodo sandbox
        run: |
          RECORD_ID=$(zenodraft --sandbox deposition create concept)
          if [ -z "$RECORD_ID" ]
              then
                  exit 1 
          fi
          echo "RECORD_ID is: $RECORD_ID"



      - name: test showing the complete details for the draft deposition
        run: |
          zenodraft --sandbox deposition show details $RECORD_ID > deposition.json
          CONCEPT_ID=$(cat deposition.json | jq '.conceptrecid' --raw-output)



      - name: test showing the id of the latest draft in the newly created concept
        run: zenodraft --sandbox deposition show latest $CONCEPT_ID



      - name: test showing the prereserved doi for the draft deposition
        run: zenodraft --sandbox deposition show prereserved $RECORD_ID



      - name: test adding a file to the draft deposition
        run: |
          echo "these are the file contents" > thefile.txt
          zenodraft --sandbox file add $RECORD_ID thefile.txt



      - name: test removing a file from the draft deposition
        run: |
          zenodraft --sandbox file delete $RECORD_ID thefile.txt



      - name: test updating the deposition metadata with information from a local file
        run: |
          echo "{\"creators\":[{\"affiliation\":\"Netherlands eScience Center\",\"name\":\"Spaaks, Jurriaan H.\",\"orcid\":\"0000-0002-7064-4069\"}],\"description\":\"Auto-generated draft deposition for CI testing of zenodraft's CLI\",\"keywords\":[\"zenodo\",\"cli\"],\"license\":{\"id\":\"Apache-2.0\"},\"title\":\"Auto-generated deposition for testing purposes\"}" > .zenodo.json
          zenodraft --sandbox metadata update $RECORD_ID .zenodo.json



      - name: test clearing the deposition metadata
        run: zenodraft --sandbox metadata clear $RECORD_ID



      - name: test deleting a draft deposition
        run: zenodraft --sandbox deposition delete $RECORD_ID


  unit:
    runs-on: ubuntu-latest
    steps:
      - name: get a copy of the repo contents
        uses: actions/checkout@v2

      - name: install the dependencies
        run: npm install

      - name: run the unit tests using jest and calculate coverage
        run: npm run test
