name: testing
on:
  pull_request:
  push:

jobs:
  cli:
    runs-on: ubuntu-latest
    steps:
      - name: get a copy of the repo contents
        uses: actions/checkout@v2

      - name: install the project's dependencies
        run: npm install

      - name: generate a distributable tarball
        run: npm run all

      - name: install the cli from the tarball
        run: sudo npm install -g zenodraft-*.tgz

      - name: create a new directory to do the testing in
        run: mkdir testing && cd testing

      - name: test creating a new draft deposition in a new collection on zenodo sandbox
        id: get_record_id
        env:
          ZENODO_SANDBOX_ACCESS_TOKEN: ${{ secrets.ZENODO_SANDBOX_ACCESS_TOKEN }}
        run: |
          RECORD_ID=$(zenodraft --sandbox deposition create in-new-collection)
          echo "::set-output name=record_id::$RECORD_ID"
        
      - name: test showing the complete details for the draft deposition
        env:
          RECORD_ID: ${{ steps.get_record_id.outputs.record_id }}
          ZENODO_SANDBOX_ACCESS_TOKEN: ${{ secrets.ZENODO_SANDBOX_ACCESS_TOKEN }}
        run: zenodraft --sandbox deposition show details $RECORD_ID

      - name: test showing the prereserved doi for the draft deposition
        env:
          RECORD_ID: ${{ steps.get_record_id.outputs.record_id }}
          ZENODO_SANDBOX_ACCESS_TOKEN: ${{ secrets.ZENODO_SANDBOX_ACCESS_TOKEN }}
        run: zenodraft --sandbox deposition show prereserved $RECORD_ID

      - name: test adding a file to the draft deposition
        env:
          RECORD_ID: ${{ steps.get_record_id.outputs.record_id }}
          ZENODO_SANDBOX_ACCESS_TOKEN: ${{ secrets.ZENODO_SANDBOX_ACCESS_TOKEN }}
        run: |
          echo "these are the file contents" > thefile.txt
          zenodraft --sandbox file add $RECORD_ID thefile.txt

      # - name: 
      #   run: 
      # - name: 
      #   run: 
      # - name: 
      #   run: 
      # - name: 
      #   run: 
      # - name: 
      #   run: 
      # - name: 
      #   run: 
      # - name: 
      #   run: 
      # - name: 
      #   run: 
      # 
